"""Plume compile — regenerate GameData/zzzz_EngineEditor/ from the plume manifest.

Phase-2, Case A only (docs/PlumeEditorDesign.md §5e). This is the ONLY module that writes
plumes to GameData, and it runs solely from an explicit POST /api/plume/compile (the user
clicking "Compile / Apply"). It:

  1. Writes EngineEditor_templates.cfg — every custom template as an EFFECTTEMPLATE
     (tool-only keys stripped: `_eeDisabled`; effects flagged `_eeDisabled=true` omitted).
  2. Writes one ee_plume_<part>.cfg per assigned engine — a Case-A `@PART[...]:FINAL`
     ModuleB9PartSwitch (moduleID=eePlumeSwitch) with a "Stock" default subtype + one
     subtype per variant that overrides the part's ModuleWaterfallFX TEMPLATE.
  3. VALIDATES first (docs/ModuleManager.md §7 lint). On ANY violation nothing is written.

Idempotent: our own artifacts (EngineEditor_templates.cfg + ee_plume_*.cfg) are rewritten
each run and stale ones removed; other files in the folder (e.g. /api/save_patch output) are
left untouched.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
KSP = os.path.dirname(os.path.dirname(HERE))
OUT_DIR = os.path.join(KSP, 'GameData', 'zzzz_EngineEditor')

TEMPLATES_FILE = 'EngineEditor_templates.cfg'
ENGINE_PREFIX = 'ee_plume_'
SWITCH_MODULE_ID = 'eePlumeSwitch'
VARIANT_PREFIX = 'ee_variant_'
ENGINE_SWITCH_MODULE_ID = 'eeEngineSwitch'
# §10.1 — the ModuleWaterfallFX we mint for engines that ship without one.
MINT_WF_MODULE_ID = 'eeWaterfall'


class CompileError(Exception):
    def __init__(self, errors):
        self.errors = errors
        super().__init__('; '.join(errors))


# ---------------- cfg serialization (port of plumelib.js serialize) ----------------

def _is_disabled(node):
    for k, v in node.get('k', []):
        if k == '_eeDisabled' and v == 'true':
            return True
    return False


def _serialize(node, depth, out):
    """Serialize a {h,k,c} node to cfg text lines. Skips _eeDisabled keys and skips whole
    EFFECT children flagged `_eeDisabled=true`."""
    pad = '  ' * depth
    out.append(pad + node['h'])
    out.append(pad + '{')
    for k, v in node.get('k', []):
        if k == '_eeDisabled':
            continue
        out.append(pad + '  ' + str(k) + ' = ' + str(v))
    for c in node.get('c', []):
        if c.get('h') == 'EFFECT' and _is_disabled(c):
            continue
        _serialize(c, depth + 1, out)
    out.append(pad + '}')


def _set_key(node, key, value):
    for kv in node['k']:
        if kv[0] == key:
            kv[1] = value
            return
    node['k'].append([key, value])


def _deep(node):
    import json
    return json.loads(json.dumps(node))


def template_cfg(manifest):
    """The EngineEditor_templates.cfg body: each custom template as an EFFECTTEMPLATE whose
    templateName is forced to the custom name."""
    out = ['// Generated by EngineEditor — do not edit by hand.',
           '// Custom Waterfall templates (source of truth: EngineEditor/data/plume_project.json).', '']
    for name in sorted(manifest.get('templates', {})):
        tree = _deep(manifest['templates'][name]['tree'])
        tree['h'] = 'EFFECTTEMPLATE'
        _set_key(tree, 'templateName', name)
        _serialize(tree, 0, out)
        out.append('')
    return '\n'.join(out) + '\n'


def engine_cfg(part, eng):
    """A single Case-A @PART[...]:FINAL B9PS plume switcher."""
    L = []
    L.append('// Generated by EngineEditor — do not edit by hand.')
    L.append('@PART[%s]:FINAL' % part)
    L.append('{')
    L.append('  MODULE')
    L.append('  {')
    L.append('    name = ModuleB9PartSwitch')
    L.append('    moduleID = %s' % SWITCH_MODULE_ID)
    L.append('    switcherDescription = EngineEditor Plume')
    wf_id = eng.get('wfModuleID', '')
    for v in eng.get('variants', []):
        name = v.get('name', '')
        L.append('    SUBTYPE')
        L.append('    {')
        L.append('      name = %s' % name)
        if name != 'Stock' and v.get('template'):
            L.append('      MODULE')
            L.append('      {')
            L.append('        IDENTIFIER')
            L.append('        {')
            L.append('          name = ModuleWaterfallFX')
            L.append('          moduleID = %s' % wf_id)
            L.append('        }')
            L.append('        DATA')
            L.append('        {')
            L.append('          !TEMPLATE,*{}')
            L.append('          TEMPLATE')
            L.append('          {')
            L.append('            templateName = %s' % v.get('template'))
            L.append('            overrideParentTransform = %s' % (v.get('overrideParentTransform', '') or ''))
            L.append('            position = %s' % (v.get('position', '0,0,0') or '0,0,0'))
            L.append('            rotation = %s' % (v.get('rotation', '0,0,0') or '0,0,0'))
            L.append('            scale = %s' % (v.get('scale', '1,1,1') or '1,1,1'))
            L.append('          }')
            L.append('        }')
            L.append('      }')
        L.append('    }')
    L.append('  }')
    L.append('}')
    return '\n'.join(L) + '\n'


# ---------------- Case-B cfg generation (docs/PlumeEditorDesign.md §5f) ----------------

def _template_block(plume, indent):
    """Emit a TEMPLATE { … } block at the given indent depth."""
    pad = '  ' * indent
    return [
        pad + 'TEMPLATE',
        pad + '{',
        pad + '  templateName = %s' % plume.get('template'),
        pad + '  overrideParentTransform = %s' % (plume.get('overrideParentTransform', '') or ''),
        pad + '  position = %s' % (plume.get('position', '0,0,0') or '0,0,0'),
        pad + '  rotation = %s' % (plume.get('rotation', '0,0,0') or '0,0,0'),
        pad + '  scale = %s' % (plume.get('scale', '1,1,1') or '1,1,1'),
        pad + '}',
    ]


def _subtype_edit_block(plume, has_override, wf_id, indent):
    """The inner edit that swaps a subtype's plume. If the subtype already has exactly one WF
    override MODULE, edit it in place (`@MODULE:HAS[@IDENTIFIER[ModuleWaterfallFX]]{@DATA{…}}`);
    otherwise ADD a MODULE override. `indent` = depth of the lines (inside the @SUBTYPE body)."""
    pad = '  ' * indent
    L = []
    if has_override:
        L.append(pad + '@MODULE:HAS[@IDENTIFIER[ModuleWaterfallFX]]')
        L.append(pad + '{')
        L.append(pad + '  @DATA')
        L.append(pad + '  {')
        L.append(pad + '    !TEMPLATE,*{}')
        L += _template_block(plume, indent + 2)
        L.append(pad + '  }')
        L.append(pad + '}')
    else:
        L.append(pad + 'MODULE')
        L.append(pad + '{')
        L.append(pad + '  IDENTIFIER')
        L.append(pad + '  {')
        L.append(pad + '    name = ModuleWaterfallFX')
        L.append(pad + '    moduleID = %s' % wf_id)
        L.append(pad + '  }')
        L.append(pad + '  DATA')
        L.append(pad + '  {')
        L.append(pad + '    !TEMPLATE,*{}')
        L += _template_block(plume, indent + 2)
        L.append(pad + '  }')
        L.append(pad + '}')
    return L


def engine_cfg_b(part, eng, ctx):
    """A single Case-B @PART[…]:FINAL block editing the existing plume switcher in place.
    Emits, in order: base-plume edits, subtype retextures, then added variants (§5f)."""
    caseb = (ctx or {}).get('caseB') or {}
    sub_detail = {s['name']: s for s in caseb.get('subtypes', [])}
    b9 = eng.get('b9ModuleID', '')
    wf = eng.get('wfModuleID', '')

    L = ['// Generated by EngineEditor — do not edit by hand.',
         '// Case B: edits the engine\'s EXISTING plume switcher (no parallel B9PS).',
         '@PART[%s]:FINAL' % part, '{']

    # (edit base / default plume) — @MODULE[ModuleWaterfallFX]:HAS[#moduleID[<wf>]]
    base = eng.get('editBase')
    if base and base.get('template'):
        L.append('  @MODULE[ModuleWaterfallFX]:HAS[#moduleID[%s]]' % wf)
        L.append('  {')
        L.append('    !TEMPLATE,*{}')
        L += _template_block(base, 2)
        L.append('  }')

    # (retexture existing subtypes) + (add variants) — both go through the B9PS selector
    edit_subs = eng.get('editSubtypes') or {}
    add_vars = eng.get('addVariants') or []
    if edit_subs or add_vars:
        L.append('  @MODULE[ModuleB9PartSwitch]:HAS[#moduleID[%s]]' % b9)
        L.append('  {')
        for sub in sorted(edit_subs):
            plume = edit_subs[sub]
            det = sub_detail.get(sub, {})
            has_ovr = bool(det.get('hasOverride')) and det.get('overrideCount', 0) == 1
            L.append('    @SUBTYPE[%s]' % sub)
            L.append('    {')
            L += _subtype_edit_block(plume, has_ovr, wf, 3)
            L.append('    }')
        for v in add_vars:
            copy_from = v.get('copyFrom', '')
            det = sub_detail.get(copy_from, {})
            # the copy inherits copyFrom's override state
            has_ovr = bool(det.get('hasOverride')) and det.get('overrideCount', 0) == 1
            L.append('    +SUBTYPE[%s]' % copy_from)
            L.append('    {')
            L.append('      @name = %s' % v.get('name', ''))
            L += _subtype_edit_block(v, has_ovr, wf, 3)
            L.append('    }')
        L.append('  }')

    L.append('}')
    return '\n'.join(L) + '\n'


# ---------------- Engine-config VARIANT generation (docs/PlumeEditorDesign.md §7) ----------------

def _engine_data_body(fields, propellants, edit, pad):
    """The writes inside a DATA (or @DATA) block. `edit`=True => MM edit-or-create form
    (`%scalar`, `!node{} node{}`); `edit`=False => plain writes into a brand-new DATA."""
    fields = fields or {}
    L = []
    op = '%' if edit else ''
    for k in ('maxThrust', 'minThrust', 'heatProduction'):
        v = fields.get(k)
        if v not in (None, ''):
            L.append(pad + op + '%s = %s' % (k, v))
    isp = fields.get('ispCurve') or []
    if isp:
        if edit:
            L.append(pad + '!atmosphereCurve {}')
        L.append(pad + 'atmosphereCurve')
        L.append(pad + '{')
        for pair in isp:
            L.append(pad + '  key = %s %s' % (pair[0], pair[1]))
        L.append(pad + '}')
    if propellants is not None:
        if edit:
            L.append(pad + '!PROPELLANT,*{}')
        for p in propellants:
            L.append(pad + 'PROPELLANT')
            L.append(pad + '{')
            L.append(pad + '  name = %s' % p.get('name', ''))
            L.append(pad + '  ratio = %s' % p.get('ratio', ''))
            dg = p.get('DrawGauge', '')
            if dg not in (None, ''):
                L.append(pad + '  DrawGauge = %s' % dg)
            L.append(pad + '}')
    return L


def _engine_data_module(eng_mod, fields, propellants, has_override, indent):
    """The engine-DATA edit block (§7.6.1). If copyFrom already has exactly one engine override
    MODULE (`has_override`), edit it in place (`@MODULE:HAS[@IDENTIFIER[<engMod>]]{@DATA{…}}` with
    %/! writes). Otherwise add a fresh MODULE with a brand-new DATA (plain writes)."""
    pad = '  ' * indent
    L = []
    if has_override:
        L.append(pad + '@MODULE:HAS[@IDENTIFIER[%s]]' % eng_mod)
        L.append(pad + '{')
        L.append(pad + '  @DATA')
        L.append(pad + '  {')
        L += _engine_data_body(fields, propellants, True, pad + '    ')
        L.append(pad + '  }')
        L.append(pad + '}')
    else:
        L.append(pad + 'MODULE')
        L.append(pad + '{')
        L.append(pad + '  IDENTIFIER')
        L.append(pad + '  {')
        L.append(pad + '    name = %s' % eng_mod)
        L.append(pad + '  }')
        L.append(pad + '  DATA')
        L.append(pad + '  {')
        L += _engine_data_body(fields, propellants, False, pad + '    ')
        L.append(pad + '  }')
        L.append(pad + '}')
    return L


def _scale_transform_blocks(model_scale, root_transforms, indent):
    """TRANSFORM { name = <root> scaleOffset = <modelScale> } per root transform (§8.4)."""
    pad = '  ' * indent
    L = []
    for root in root_transforms:
        L.append(pad + 'TRANSFORM')
        L.append(pad + '{')
        L.append(pad + '  name = %s' % root)
        L.append(pad + '  scaleOffset = %s' % model_scale)
        L.append(pad + '}')
    return L


def _minted_wf_module(plume, indent):
    """§10.1 — a part-level ModuleWaterfallFX (moduleID=eeWaterfall) minted for engines that ship
    with no Waterfall module. Seeded with the first plume-carrying variant's TEMPLATE + attach so
    the module has a valid default; per-subtype B9PS overrides then swap/disable it."""
    pad = '  ' * indent
    L = [
        pad + 'MODULE',
        pad + '{',
        pad + '  name = ModuleWaterfallFX',
        pad + '  moduleID = %s' % MINT_WF_MODULE_ID,
        pad + '  CONTROLLER',
        pad + '  {',
        pad + '    name = atmosphereDepth',
        pad + '    linkedTo = atmosphere_density',
        pad + '  }',
        pad + '  CONTROLLER',
        pad + '  {',
        pad + '    name = throttle',
        pad + '    linkedTo = throttle',
        pad + '  }',
        pad + '  CONTROLLER',
        pad + '  {',
        pad + '    name = random',
        pad + '    linkedTo = random',
        pad + '    range = -1,1',
        pad + '  }',
    ]
    L += _template_block(plume, indent + 1)
    L.append(pad + '}')
    return L


def _wf_disable_block(wf_id, indent):
    """§10.1 — B9PS module enable/disable: turn OFF the (minted) ModuleWaterfallFX inside a subtype
    so stock/plumeless subtypes don't show the seeded default plume. Verified real-world form
    (ModuleManager.ConfigCache): `MODULE { moduleActive = false  IDENTIFIER { name=..  moduleID=.. } }`."""
    pad = '  ' * indent
    return [
        pad + 'MODULE',
        pad + '{',
        pad + '  moduleActive = false',
        pad + '  IDENTIFIER',
        pad + '  {',
        pad + '    name = ModuleWaterfallFX',
        pad + '    moduleID = %s' % wf_id,
        pad + '  }',
        pad + '}',
    ]


def engine_variant_cfg(part, ev, ctx):
    """A single @PART[…]:FINAL block adding full engine-config B9PS subtypes (§7.6). Each subtype
    either `+SUBTYPE`s into the part's existing engine-aspect B9PS (b9ModuleID set AND copyFrom
    non-null) or is minted into a fresh `eeEngineSwitch` B9PS (b9ModuleID null OR copyFrom null).

    §10.1: when the part ships NO ModuleWaterfallFX (ctx.wfModuleID empty) but ≥1 variant sets a
    plume, mint a part-level ModuleWaterfallFX (moduleID=eeWaterfall) seeded with the first
    plume-carrying variant's template; plumeless/stock subtypes disable it (moduleActive=false)."""
    ctx = ctx or {}
    target = ev.get('targetModule') or ctx.get('targetModule') or 'ModuleEnginesFX'
    b9 = ev.get('b9ModuleID')
    wf = ctx.get('wfModuleID', '') or ''
    mint_wf = not wf
    if mint_wf:
        wf = MINT_WF_MODULE_ID
    # first plume-carrying variant (in declared order) seeds the minted WF module's default TEMPLATE.
    first_plume = None
    for s in ev.get('subtypes', []):
        p = s.get('plume')
        if p and p.get('template'):
            first_plume = p
            break
    do_mint_wf = mint_wf and first_plume is not None
    sub_detail = {s.get('name'): s for s in ctx.get('subtypes', [])}

    existing = []
    mint = []
    for s in ev.get('subtypes', []):
        if b9 and s.get('copyFrom'):
            existing.append(s)
        else:
            mint.append(s)

    L = ['// Generated by EngineEditor — do not edit by hand.',
         '// Engine-config variants: full new B9PS subtypes (thrust/ISP/heat/fuel + optional plume).',
         '@PART[%s]:FINAL' % part, '{']

    # §10.1: mint the part-level ModuleWaterfallFX once (before the B9PS section) when the part has
    # none and at least one variant carries a plume.
    if do_mint_wf:
        L += _minted_wf_module(first_plume, 1)

    if existing:
        L.append('  @MODULE[ModuleB9PartSwitch]:HAS[#moduleID[%s]]' % b9)
        L.append('  {')
        # Emit the +SUBTYPE copies FIRST so each snapshots its copyFrom BEFORE the shipped-subtype
        # WF-disable edits below rename-immune it (+SUBTYPE snapshots at copy time; the @SUBTYPE
        # disables target the original names, and the copies are renamed via @name).
        for s in existing:
            cf = s.get('copyFrom')
            det = sub_detail.get(cf, {})
            has_ovr = bool(det.get('hasEngineOverride')) and det.get('overrideCount', 0) == 1
            L.append('    +SUBTYPE[%s]' % cf)
            L.append('    {')
            L.append('      @name = %s' % s.get('name', ''))
            transforms = s.get('transforms')
            if isinstance(transforms, list):
                L.append('      !transform = _')
                for t in transforms:
                    L.append('      transform = %s' % t)
            if s.get('title'):
                L.append('      %title = ' + str(s['title']))
            if s.get('addedMass'):
                L.append('      %addedMass = ' + str(s['addedMass']))
            if s.get('addedCost'):
                L.append('      %addedCost = ' + str(s['addedCost']))
            L += _engine_data_module(target, s.get('fields'), s.get('propellants'), has_ovr, 3)
            if s.get('plume'):
                # copyFrom's copied subtype may already carry a WF override → edit it in place;
                # otherwise add one. Mirrors the plume Case-B logic (§7.10). When we minted the WF
                # module, the copy has no override of it → add one (wf_ovr stays False).
                wf_ovr = (not mint_wf) and bool(det.get('hasWfOverride')) and det.get('wfOverrideCount', 0) == 1
                L += _subtype_edit_block(s['plume'], wf_ovr, wf, 3)
            elif do_mint_wf:
                # §10.1: a plumeless copy would inherit the minted WF's seeded plume — disable it.
                L += _wf_disable_block(wf, 3)
            model_scale = s.get('modelScale')
            root_transforms = ctx.get('rootTransforms') or []
            if model_scale and root_transforms:
                # copyFrom may already carry TRANSFORM blocks (scaleOffsets non-empty) — replace
                # rather than stack (§8.4).
                if det.get('scaleOffsets'):
                    L.append('      !TRANSFORM,*{}')
                L += _scale_transform_blocks(model_scale, root_transforms, 3)
            L.append('    }')
        # §10.1: after the copies, disable the minted WF in every SHIPPED subtype so stock configs
        # stay visually stock.
        if do_mint_wf:
            for det in ctx.get('subtypes', []):
                if det.get('isBase'):
                    continue
                L.append('    @SUBTYPE[%s]' % det.get('name'))
                L.append('    {')
                L += _wf_disable_block(wf, 3)
                L.append('    }')
        L.append('  }')

    if mint:
        L.append('  MODULE')
        L.append('  {')
        L.append('    name = ModuleB9PartSwitch')
        L.append('    moduleID = %s' % ENGINE_SWITCH_MODULE_ID)
        L.append('    switcherDescription = EngineEditor Config')
        L.append('    SUBTYPE')
        L.append('    {')
        L.append('      name = Stock')
        # §10.1: the minted WF module is active-by-default (it carries a seeded TEMPLATE) — the
        # Stock subtype must disable it so "Stock" stays visually stock.
        if do_mint_wf:
            L += _wf_disable_block(wf, 3)
        L.append('    }')
        for s in mint:
            L.append('    SUBTYPE')
            L.append('    {')
            L.append('      name = %s' % s.get('name', ''))
            for t in (s.get('transforms') or []):
                L.append('      transform = %s' % t)
            if s.get('title'):
                L.append('      title = %s' % s['title'])
            if s.get('addedMass'):
                L.append('      addedMass = %s' % s['addedMass'])
            if s.get('addedCost'):
                L.append('      addedCost = %s' % s['addedCost'])
            L += _engine_data_module(target, s.get('fields'), s.get('propellants'), False, 3)
            if s.get('plume'):
                L += _subtype_edit_block(s['plume'], False, wf, 3)
            elif do_mint_wf:
                # §10.1: a plumeless minted subtype must also hide the seeded default plume.
                L += _wf_disable_block(wf, 3)
            model_scale = s.get('modelScale')
            root_transforms = ctx.get('rootTransforms') or []
            if model_scale and root_transforms:
                L += _scale_transform_blocks(model_scale, root_transforms, 3)
            L.append('    }')
        L.append('  }')

    L.append('}')
    return '\n'.join(L) + '\n'


# ---------------- validation (docs/ModuleManager.md §7) ----------------

def _is_num(s):
    try:
        float(s)
        return True
    except (TypeError, ValueError):
        return False


def _validate_engine_variants(part, ev, ctx, known_templates, errors):
    """Lint per §7.6.2. Appends error strings; refuses (caller writes nothing) on any violation."""
    target = ev.get('targetModule')
    ctx_target = ctx.get('targetModule')
    if not ctx_target:
        errors.append('%s: part has no engine module (ModuleEnginesFX/ModuleEngines); refused' % part)
        return
    if target != ctx_target:
        errors.append('%s: variant targetModule %r != the part\'s engine module %r'
                      % (part, target, ctx_target))
    if ctx.get('engineB9Count', 0) > 1:
        errors.append('%s: %d B9PS DATA-target the engine module — ambiguous engine-config B9PS; refused'
                      % (part, ctx.get('engineB9Count')))

    engine_b9 = ctx.get('engineB9')
    real_subs = {s.get('name') for s in ctx.get('subtypes', []) if not s.get('isBase')}
    sub_detail = {s.get('name'): s for s in ctx.get('subtypes', [])}
    b9 = ev.get('b9ModuleID')
    subtypes = ev.get('subtypes', [])
    mint_path = (not b9) or any(not s.get('copyFrom') for s in subtypes)

    if b9:
        owner = (engine_b9 or {}).get('moduleID')
        if not engine_b9 or b9 != owner:
            errors.append('%s: b9ModuleID %r != the engine-aspect owner %r' % (part, b9, owner))
        for s in subtypes:
            cf = s.get('copyFrom')
            if cf:
                if cf not in real_subs:
                    errors.append('%s: variant %r copies non-existent subtype %r'
                                  % (part, s.get('name'), cf))
                elif sub_detail.get(cf, {}).get('overrideCount', 0) > 1:
                    errors.append('%s: variant %r copies subtype %r which has >1 engine overrides — '
                                  'ambiguous selector; refused' % (part, s.get('name'), cf))

    if mint_path:
        if engine_b9:
            errors.append('%s: cannot mint a parallel engine-config B9PS — %r already owns the engine '
                          'aspect; refused' % (part, (engine_b9 or {}).get('moduleID')))
        if ENGINE_SWITCH_MODULE_ID in (ctx.get('b9ModuleIDs') or []):
            errors.append('%s: moduleID %r already exists on the part — B9PS collision; refused'
                          % (part, ENGINE_SWITCH_MODULE_ID))

    seen = set()
    for s in subtypes:
        name = s.get('name', '')
        if name == 'Stock':
            errors.append('%s: variant name "Stock" is reserved' % part)
        if name in seen:
            errors.append('%s: duplicate variant name %r' % (part, name))
        seen.add(name)
        if name in real_subs:
            errors.append('%s: variant %r collides with an existing subtype name' % (part, name))

        fields = s.get('fields') or {}
        for k in ('maxThrust', 'minThrust', 'heatProduction'):
            if fields.get(k) not in (None, '') and not _is_num(fields.get(k)):
                errors.append('%s: variant %r %s %r is not numeric' % (part, name, k, fields.get(k)))
        for pair in (fields.get('ispCurve') or []):
            if len(pair) != 2 or not _is_num(pair[0]) or not _is_num(pair[1]):
                errors.append('%s: variant %r has a non-numeric ISP curve entry %r' % (part, name, pair))

        props = s.get('propellants')
        if props is not None:
            for p in props:
                if not (p.get('name') or '').strip():
                    errors.append('%s: variant %r has a propellant with no name' % (part, name))
                if not _is_num(p.get('ratio')):
                    errors.append('%s: variant %r propellant %r has a non-numeric ratio %r'
                                  % (part, name, p.get('name'), p.get('ratio')))

        for fld in ('addedMass', 'addedCost'):
            if s.get(fld) not in (None, '') and not _is_num(s.get(fld)):
                errors.append('%s: variant %r %s %r is not numeric' % (part, name, fld, s.get(fld)))

        transforms = s.get('transforms')
        if transforms:
            pool = ctx.get('transformPool') or []
            if not pool:
                errors.append('%s: variant %r: no switchable model elements known for this part'
                              % (part, name))
            else:
                for t in transforms:
                    if t not in pool:
                        errors.append('%s: variant %r references unknown transform %r'
                                      % (part, name, t))

        model_scale = s.get('modelScale')
        if model_scale:
            if not _is_num(model_scale) or float(model_scale) <= 0:
                errors.append('%s: variant %r modelScale %r is not a positive number'
                              % (part, name, model_scale))
            elif not (ctx.get('rootTransforms') or []):
                errors.append('%s: variant %r sets modelScale but model root unknown for %s'
                              % (part, name, part))

        plume = s.get('plume')
        if plume:
            # §10.1: a part with NO ModuleWaterfallFX is no longer refused — we mint one
            # (moduleID=eeWaterfall). Only require the minted moduleID not collide with an existing
            # module on the part.
            if not ctx.get('wfModuleID') and MINT_WF_MODULE_ID in (
                    (ctx.get('b9ModuleIDs') or []) + [ctx.get('wfModuleID') or '']):
                errors.append('%s: cannot mint ModuleWaterfallFX — moduleID %r already exists on the '
                              'part; refused' % (part, MINT_WF_MODULE_ID))
            if plume.get('template') not in known_templates:
                errors.append('%s: variant %r plume references unknown template %r'
                              % (part, name, plume.get('template')))
            # +SUBTYPE path: if copyFrom already has >1 WF override, the edit-in-place selector is
            # ambiguous — refuse (mirrors the plume Case-B lint). §7.10.
            cf = s.get('copyFrom')
            if b9 and cf and sub_detail.get(cf, {}).get('wfOverrideCount', 0) > 1:
                errors.append('%s: variant %r sets a plume but copies subtype %r which has >1 '
                              'ModuleWaterfallFX overrides — ambiguous selector; refused'
                              % (part, name, cf))

    if not subtypes:
        errors.append('%s: no engine variants defined' % part)

def _validate_case_a(part, eng, ctx, known_templates, errors):
    wf_id = eng.get('wfModuleID', '')
    if wf_id not in (ctx.get('wfModuleIDs') or []):
        errors.append('%s: wfModuleID %r matches no ModuleWaterfallFX on the part (lint §7.7)'
                      % (part, wf_id))
    if SWITCH_MODULE_ID in (ctx.get('b9ModuleIDs') or []):
        errors.append('%s: moduleID %r already exists on the part — B9PS collision (lint §7.7)'
                      % (part, SWITCH_MODULE_ID))
    has_variant = False
    for v in eng.get('variants', []):
        if v.get('name') == 'Stock':
            continue
        has_variant = True
        tn = v.get('template')
        if tn not in known_templates:
            errors.append('%s: variant %r references unknown template %r (lint §7.6)'
                          % (part, v.get('name'), tn))
    if not has_variant:
        errors.append('%s: no plume variants assigned (only Stock)' % part)


def _validate_case_b(part, eng, ctx, known_templates, errors):
    caseb = ctx.get('caseB') or {}
    sub_detail = {s['name']: s for s in caseb.get('subtypes', [])}
    real_subs = set(sub_detail)
    b9 = eng.get('b9ModuleID', '')
    wf = eng.get('wfModuleID', '')
    if b9 not in (ctx.get('b9ModuleIDs') or []):
        errors.append('%s: b9ModuleID %r matches no ModuleB9PartSwitch on the part (lint §7.7)'
                      % (part, b9))
    if wf not in (ctx.get('wfModuleIDs') or []):
        errors.append('%s: wfModuleID %r matches no ModuleWaterfallFX on the part (lint §7.7)'
                      % (part, wf))

    def _check_template(label, tn):
        if tn not in known_templates:
            errors.append('%s: %s references unknown template %r (lint §7.6)' % (part, label, tn))

    base = eng.get('editBase')
    if base and base.get('template'):
        _check_template('base plume', base.get('template'))

    for sub in sorted(eng.get('editSubtypes') or {}):
        plume = eng['editSubtypes'][sub]
        if sub not in real_subs:
            errors.append('%s: editSubtypes references non-existent subtype %r' % (part, sub))
            continue
        det = sub_detail.get(sub, {})
        if det.get('hasOverride') and det.get('overrideCount', 0) > 1:
            errors.append('%s: subtype %r has %d ModuleWaterfallFX overrides — the '
                          '@MODULE:HAS[@IDENTIFIER[ModuleWaterfallFX]] selector is ambiguous '
                          '(lint §7.7); refused' % (part, sub, det.get('overrideCount')))
        _check_template('subtype %r' % sub, plume.get('template'))

    seen = set()
    for v in eng.get('addVariants') or []:
        name = v.get('name', '')
        copy_from = v.get('copyFrom', '')
        if name in seen:
            errors.append('%s: duplicate added-variant name %r' % (part, name))
        seen.add(name)
        if name in real_subs:
            errors.append('%s: added-variant %r collides with an existing subtype name' % (part, name))
        if copy_from not in real_subs:
            errors.append('%s: added-variant %r copies non-existent subtype %r'
                          % (part, name, copy_from))
        else:
            det = sub_detail.get(copy_from, {})
            if det.get('hasOverride') and det.get('overrideCount', 0) > 1:
                errors.append('%s: added-variant %r copies subtype %r which has %d WF overrides — '
                              'ambiguous selector (lint §7.7); refused'
                              % (part, name, copy_from, det.get('overrideCount')))
        _check_template('added-variant %r' % name, v.get('template'))

    if not (base and base.get('template')) and not (eng.get('editSubtypes')) and not (eng.get('addVariants')):
        errors.append('%s: no Case-B edits assigned' % part)


def validate(manifest, mod_template_names, part_ctx, variant_ctx=None):
    """Return a list of error strings (empty == OK).

    part_ctx: {part: {'case':'A'|'B'|'none', 'wfModuleIDs':[...], 'b9ModuleIDs':[...],
                      'caseB': {…}|None}}
    variant_ctx: {part: engine_variant_info(part)} — one entry per part in engineVariants.
    """
    variant_ctx = variant_ctx or {}
    errors = []
    custom = set(manifest.get('templates', {}))
    known_templates = custom | set(mod_template_names)

    for part, eng in manifest.get('engines', {}).items():
        ctx = part_ctx.get(part)
        if ctx is None:
            errors.append('%s: part not found in the compiled cache' % part)
            continue
        if ctx.get('case') == 'none':
            errors.append('%s: engine has no ModuleWaterfallFX to switch' % part)
            continue
        assigned_case = eng.get('case', 'A')
        if assigned_case != ctx.get('case'):
            errors.append('%s: assignment is Case %s but the engine is Case %s — refused'
                          % (part, assigned_case, ctx.get('case')))
            continue
        if assigned_case == 'A':
            _validate_case_a(part, eng, ctx, known_templates, errors)
        else:
            _validate_case_b(part, eng, ctx, known_templates, errors)

    for part, ev in manifest.get('engineVariants', {}).items():
        ctx = variant_ctx.get(part)
        if ctx is None:
            errors.append('%s: part not found in the compiled cache' % part)
            continue
        _validate_engine_variants(part, ev, ctx, known_templates, errors)
    return errors


# ---------------- compile ----------------

def compile_all(manifest, mod_template_names, part_ctx, variant_ctx=None, out_dir=OUT_DIR):
    """Validate, then rewrite our artifacts in out_dir. Raises CompileError (writes nothing)
    on any lint violation. Returns a summary dict. `variant_ctx` (default {}) is
    {part: engine_variant_info(part)} for every part in manifest['engineVariants']; callers that
    pass none behave exactly as before."""
    variant_ctx = variant_ctx or {}
    errors = validate(manifest, mod_template_names, part_ctx, variant_ctx)
    if errors:
        raise CompileError(errors)

    files = {}  # basename -> content
    files[TEMPLATES_FILE] = template_cfg(manifest)
    assigned = []
    for part in sorted(manifest.get('engines', {})):
        eng = manifest['engines'][part]
        if eng.get('case') == 'B':
            # skip if no real Case-B edit
            if not (eng.get('editBase') and eng['editBase'].get('template')) \
               and not eng.get('editSubtypes') and not eng.get('addVariants'):
                continue
            files[ENGINE_PREFIX + part + '.cfg'] = engine_cfg_b(part, eng, part_ctx.get(part))
            assigned.append(part)
            continue
        # Case A: skip engines that only have Stock (no real assignment) — nothing to emit
        if not any(v.get('name') != 'Stock' for v in eng.get('variants', [])):
            continue
        files[ENGINE_PREFIX + part + '.cfg'] = engine_cfg(part, eng)
        assigned.append(part)

    # Engine-config variants — one ee_variant_<part>.cfg per part with subtypes.
    variant_parts = []
    for part in sorted(manifest.get('engineVariants', {})):
        ev = manifest['engineVariants'][part]
        if not ev.get('subtypes'):
            continue
        files[VARIANT_PREFIX + part + '.cfg'] = engine_variant_cfg(part, ev, variant_ctx.get(part))
        variant_parts.append(part)

    # If there are no custom templates AND no assignments, don't leave an empty templates file.
    if not manifest.get('templates') and not assigned and not variant_parts:
        files.pop(TEMPLATES_FILE, None)

    os.makedirs(out_dir, exist_ok=True)
    # remove stale artifacts we own that aren't in the new set
    for fn in os.listdir(out_dir):
        if fn == TEMPLATES_FILE or fn.startswith(ENGINE_PREFIX) or fn.startswith(VARIANT_PREFIX):
            if fn not in files:
                try:
                    os.remove(os.path.join(out_dir, fn))
                except OSError:
                    pass

    written = []
    for fn, content in files.items():
        with open(os.path.join(out_dir, fn), 'w', encoding='utf-8', newline='\n') as f:
            f.write(content)
        written.append('GameData/zzzz_EngineEditor/' + fn)

    return {'ok': True, 'written': sorted(written), 'assignedEngines': assigned,
            'variantEngines': variant_parts,
            'customTemplates': sorted(manifest.get('templates', {}))}
